import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountrystatesService {
  countries: string[] = ['Ukraine', 'United States', 'United Kingdom'];
  states: {
    Ukraine: string[];
    'United States': string[];
    'United Kingdom': string[];
  } = {
    Ukraine: [
      'Autonomous Republic of Crimea',
      'Cherkasy Oblast',
      'Chernihiv Oblast',
      'Chernivtsi Oblast',
      'Dnipropetrovsk Oblast',
      'Donetsk Oblast',
      'Ivano-Frankivsk Oblast',
      'Kharkiv Oblast',
      'Kherson Oblast',
      'Khmelnytskyi Oblast',
      'Kyiv Oblast',
      'Kirovohrad Oblast',
      'Luhansk Oblast',
      'Lviv Oblast',
      'Mykolaiv Oblast',
      'Odessa Oblast',
      'Poltava Oblast',
      'Rivne Oblast',
      'Sumy Oblast',
      'Ternopil Oblast',
      'Vinnytsia Oblast',
      'Volyn Oblast',
      'Zakarpattia Oblast',
      'Zaporizhzhia Oblast',
      'Zhytomyr Oblast'
    ],
    'United States': [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming'
    ],
    'United Kingdom': [
      'Avon',
      'Bedfordshire',
      'Berkshire',
      'Buckinghamshire',
      'Cambridgeshire',
      'Cheshire',
      'Cleveland',
      'Cornwall',
      'Cumbria',
      'Derbyshire',
      'Devon',
      'Dorset',
      'Durham',
      'East Sussex',
      'Essex',
      'Gloucestershire',
      'Hampshire',
      'Herefordshire',
      'Hertfordshire',
      'Isle of Wight',
      'Kent',
      'Lancashire',
      'Leicestershire',
      'Lincolnshire',
      'London',
      'Merseyside',
      'Middlesex',
      'Norfolk',
      'Northamptonshire',
      'Northumberland',
      'North Humberside',
      'North Yorkshire',
      'Nottinghamshire',
      'Oxfordshire',
      'Rutland',
      'Shropshire',
      'Somerset',
      'South Humberside',
      'South Yorkshire',
      'Staffordshire',
      'Suffolk',
      'Surrey',
      'Tyne and Wear',
      'Warwickshire',
      'West Midlands',
      'West Sussex',
      'West Yorkshire',
      'Wiltshire',
      'Worcestershire',
      'Clwyd',
      'Dyfed',
      'Gwent',
      'Gwynedd',
      'Mid Glamorgan',
      'Powys',
      'South Glamorgan',
      'West Glamorgan',
      'Aberdeenshire',
      'Angus',
      'Argyll',
      'Ayrshire',
      'Banffshire',
      'Berwickshire',
      'Bute',
      'Caithness',
      'Clackmannanshire',
      'Dumfriesshire',
      'Dunbartonshire',
      'East Lothian',
      'Fife',
      'Inverness-shire',
      'Kincardineshire',
      'Kinross-shire',
      'Kirkcudbrightshire',
      'Lanarkshire',
      'Midlothian',
      'Moray',
      'Nairnshire',
      'Orkney',
      'Peeblesshire',
      'Perthshire',
      'Renfrewshire',
      'Ross-shire',
      'Roxburghshire',
      'Selkirkshire',
      'Shetland',
      'Stirlingshire',
      'Sutherland',
      'West Lothian',
      'Wigtownshire',
      'Antrim',
      'Armagh',
      'Down',
      'Fermanagh',
      'Londonderry',
      'Tyrone'
    ]
  };
  countryStates: string;
}
